### ISSUE TITLE
Add installation instructions and documentation to README

### ISSUE THREAD

**Issue by ddohler** [azavea/loam#18]
This should include `yarn install loam` as well as a list of functions that Loam exposes.

**Comment by CloudNiner** [comment]
If the intent is to delay including the compiled assets in the zipped releases its probably also worth adding a note that the compiled assets can be acquired by copying the contents of `lib` after checking out the project and running:
```
yarn install --pure-lockfile
yarn build
// or
npm install 
npm run build
```

**Comment by ddohler** [comment]
Yeah, I agree; #17 is supposed to cover adding compiled assets to the zipped releases but it seems likely that this will be done first since it's lower effort, so build instructions should definitely be included in the README too.
