### ISSUE TITLE
Not getting -te to work

### ISSUE THREAD

**Issue by SimonsUnikaNamn** [azavea/loam#59]
I get the error

`Error in GDALWarp: Unknown option name '-te'`

when trying to clip a raster https://gdal.org/programs/gdalwarp.html#cmdoption-gdalwarp-te

I guess it has to do with gdal-js and not with LOAM?

**Comment by ddohler** [comment]
Hey @SimonsUnikaNamn, it sounds like this is most likely a gdal-js issue, yes -- Loam does very little validation of command-line parameters and leaves most of the validation to gdal-js. However, I'm happy to try to debug here; there may be something that Loam can change to mitigate any problem with gdal-js.

If you can, are you able to share the command array that you're using? I can give it a try on my side to see if I can figure out what's going on.

Also, are you able to successfully run the same command from the command line? You'll need to add in the input and output parameters, but otherwise it should be pretty similar, i.e. `login$ gdalwarp ....`. Doing that is a good way to confirm whether there is a problem with gdal-js or whether there is an issue with your command format somehow. If you have access to GDAL 2.1, that's the version that gdal-js is based on, so it'd be especially helpful to test against that, although it is getting kind of outdated at this point.

Please let me know what you find!

**Comment by SimonsUnikaNamn** [comment]
Wow thanks for the answer, I was not very hopeful that anything would come out of it.

I can try with 2.1 tonight (using a docker image most likely) and give you the command.

**Comment by SimonsUnikaNamn** [comment]
Crap, I could not find 2.1 in a Docker image :/

This is the command I run locally
```
gdalwarp -te 261706.175883237156086 6649939.583552370779216 261982.168264129024465 6650158.605028949677944 dom1_33_oslo_3.tif clipped.tif
```
with the file I have added in this post
[dom1_33_oslo_tiny_3.zip](https://github.com/azavea/loam/files/6023466/dom1_33_oslo_tiny_3.zip)

**Comment by ddohler** [comment]
@SimonsUnikaNamn Great, thanks for this info! I'll give this a try on my end and see if I can replicate it and/or diagnose. It may be toward the end of this week or sometime next before I can get to it though.

**Comment by SimonsUnikaNamn** [comment]
Thank you for the help, I should note that I have gotten success using the [geotiffjs](https://geotiffjs.github.io/) library but there I am not able to do perfect cuts using coordinates, instead I have to manually read a byte array and do rough cuts by shaping it.
GDAL is a much nicer package to work with

**Comment by ddohler** [comment]
Yeah, that sounds similar to my motivation for working on gdal-js / Loam: geotiffjs works fine, but it's pretty low level and forces a lot of DIY, whereas GDAL already has pretty much everything you'd need packaged in it, so you don't have to reinvent the wheel. I'll try to take a look at this as soon as I can!

**Comment by SimonsUnikaNamn** [comment]
I was very happy when I found gdal-js but it was impossible for me to figure out how to call methods for things that was not given in the example, that is why I was even more happy when I found loam :)

Take your time, it is no longer super critical for me but of course it would help to have the power of GDAL in the frontend 😍

**Comment by ddohler** [comment]
Hey @SimonsUnikaNamn -- I took a look at this and I think I was able to get it to work with the `-te` option. Here's what my code looks like:

```javascript
loam.open(file)                                                                                 
          .then((opened) =>                                                                           
              opened.warp([                                                                           
                  '-te',                                                                              
                  '261706.175883237156086',                                                           
                  '6649939.583552370779216',                                                          
                  '261982.168264129024465',                                                           
                  '6650158.605028949677944',                                                          
              ])                                                                                      
          )                                                                                           
          .then((ds) => {                                                                             
              return Promise.all([                                                                    
                  ds.width(),                                                                         
                  ds.height(),                                                                        
                  ds.count(),                                                                         
                  ds.wkt(),                                                                           
                  ds.transform(),
    ...
```
Does that look similar to what you did? If I echo out the width and height of the file from Loam, I get:
<img width="741" alt="Screen Shot 2021-03-01 at 4 26 46 PM" src="https://user-images.githubusercontent.com/447977/109561286-f5b15280-7aaa-11eb-814f-38586a81ebf7.png">

That's basically the same as what I get if I run from the command-line:
```
$ gdalwarp -te 261706.175883237156086 6649939.583552370779216 261982.168264129024465 6650158.605028949677944 dom1_33_oslo_tiny_3.tif clipped.tif
Creating output file that is 92P x 73L.
Processing input file dom1_33_oslo_tiny_3.tif.
0...10...20...30...40...50...60...70...80...90...100 - done.
$ gdalinfo clipped.tif 
Driver: GTiff/GeoTIFF
Files: clipped.tif
Size is 92, 73
Coordinate System is:
PROJCS["ETRS89 / UTM zone 33N",
    GEOGCS["ETRS89",
        DATUM["European_Terrestrial_Reference_System_1989",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            TOWGS84[0,0,0,0,0,0,0],
            AUTHORITY["EPSG","6258"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4258"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",15],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","25833"]]
Origin = (261706.175883237156086,6650158.605028949677944)
Pixel Size = (2.999917183607265,-3.000294199710941)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  261706.176, 6650158.605) ( 10d44'10.12"E, 59d55'11.32"N)
Lower Left  (  261706.176, 6649939.584) ( 10d44'11.02"E, 59d55' 4.26"N)
Upper Right (  261982.168, 6650158.605) ( 10d44'27.84"E, 59d55'11.89"N)
Lower Right (  261982.168, 6649939.584) ( 10d44'28.74"E, 59d55' 4.83"N)
Center      (  261844.172, 6650049.094) ( 10d44'19.43"E, 59d55' 8.07"N)
Band 1 Block=92x22 Type=Float32, ColorInterp=Gray
```

Does any of this help?

**Comment by SimonsUnikaNamn** [comment]
Cool, hmm I must have done something strange, I will try it. Thanks a lot man!

**Comment by ddohler** [comment]
Sure thing! If you get it figured out, please let me know if there's anything that can be improved about the documentation to make this kind of thing easier. If I don't hear anything within a few weeks I'll go ahead and close this issue.

**Comment by SimonsUnikaNamn** [comment]
I have no issues so I think we can close it, thank you again :)
