### ISSUE TITLE
Asset locations

### ISSUE THREAD

**Issue by byezy** [azavea/loam#68]
"All of these files will be included in the node_modules folder after running npm install loam, but it is up to you to integrate them into your development environment and deployment processes."

Any recommendations, best practices or examples regarding deployment structure?

**Comment by ddohler** [comment]
Hi @byezy -- I'm not sure why you closed this, but to answer your question, I've had the best luck with treating some of the ancillary dependencies as large media files, similar to movie files or PDFs. For simpler builds, I've also sometimes simply symlinked from the `node_modules` folder directly into the build output. I'm hoping to add an example using create-react-app to the docs soon!
