### ISSUE TITLE
GDALDataset.bytes() is not documented

### ISSUE THREAD

**Issue by LuukMoret** [azavea/loam#87]
Is there a way to access the converted Geotiff file when using `GDALDataset.convert(args)` the same way as `gdal_translate` cli command returns a Geotiff file?

**Comment by ddohler** [comment]
Oops, you've caught a documentation bug -- you can call the `bytes()` method on the new Dataset and it'll give you back the GeoTIFF (or whatever format you've specified). That should be documented, but isn't. I'm going to leave this open and update the title to include this in the docs. Thanks!

**Comment by LuukMoret** [comment]
Great! Thanks for the fast response!

**Comment by ddohler** [comment]
This has been fixed in `develop` for a while but I just cut a new release that merges this to `master` as well, so I'm closing this.
